### Numpy (Numerical Python)

>* 벡터 및 행렬연산에 특화된 라이브러리 
* array단위로 데이터를 관리한다. 행렬(Matrix)과 유사함
* pandas와 함께 데이터분석에 많이 사용된다.
* 수치해석용 Python라이브러리
* 기본적으로 array단위로 관리 및 연산을 수행한다.

#### 참고사이트
1. home : http://www.numpy.org
2. documentation : http://docs.scipy.org.doc
3. tutrial :
   1) http://www.scipy-lectures.org/intro/numpy/index.html
   2) https://docs.scipy.org.doc/numpy/user/quickstart.html

In [3]:
# Numpy를 사용하기 위해서는 import해와야 한다.
import numpy as np
#print(dir(np))
np.__version__

'1.16.5'

### 1. 1차원 Array정의 및 사용하기

In [8]:
data = [1,2,3,4,5]
print(type(data))

# numpy의 배열(ndarray)로 변경
arr = np.array(data)
print(arr)
print(type(arr))

# upcasting : 강제형변환
arr1 = np.array([1,2,3,4.1])
arr1

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1. , 2. , 3. , 4.1])

In [17]:
# np.shape : numpy배열의 크기를 리턴
# np.shape?
a = 4
print(type(a))

a = 4,
print(type(a))

a = (4,)
print(type(a))

print(np.shape(arr1))

print(arr1.shape)
help(arr1.shape)

<class 'int'>
<class 'tuple'>
<class 'tuple'>
(4,)
(4,)
Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(sel

### 2. 2차원배열(행렬, Matrix)

In [24]:
# 2차원리스트
data = [[1,2,3], [4,5,6.0]]
print(data)

# 2차원리스트를 numpy의 2차원배열로 변환하기
arr = np.array(data)
print(type(arr))
print(arr.shape)
print(arr)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# numpy의 data type확인
print(arr.dtype)

[[1, 2, 3], [4, 5, 6.0]]
<class 'numpy.ndarray'>
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


### Numpy 연산

#### 1. numpy shape

* numpy에서 해당 array크기를 확인할 수 있는 함수이다. 이 함수는 정수를 리턴
* shpae(크기)를 확인 함으로써 numpy배열에 몇개의 데이터가 있는지 몇차원의 데이터인지를 확인한다.
* 1차원배열일경우 `(5,`)형태로, 2차원배일일 경우는 `(3,4)`의 형태로 리턴한다.

#### 2. numpy datatype

* int(8, 16, 32, 64)  : 부호가 있는 정수
* uint(8, 16, 32, 64) : 부호가 없는 정수
* float(16, 32, 64,128) : 실수
* complex(64, 128, 256) : 복소수
* bool : boolean
* string_ : 문자열
* object  : 파이썬 오브젝츠(객체)
* unicode_: 유니코드


In [32]:
# Numpy배열의 연산 
# 배열을 연산할 때는 배열의 크기가 반드시 동일해야 한다. 틀리면 에러가 발생한다.
arr1 = np.array([[1,2,3],[4,5,6]]) 
arr2 = np.array([[7,8,9],[10,11,12]]) 

print(arr1 + arr2) 
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 * 2)    # 각요소 * 2
print(arr1 ** 2)   # 각요소 ** 2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [38]:
# array의 브로드캐스트
# numpy배열에서는 동일 크기를 가져야지만 연산이 가능하지만
# numpy에서는 broadcast라는 기능을 제공해준다. 브로드캐스트라는 것은 
# 서로 크기가 다른 넘파이배열을 연산이 가능하도록 해주는 기능이다.

arr1 = np.array([[1,2,3],[4,5,6]]) 
arr2 = np.array([10,11,12])
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)

(2, 3)
(4,)


ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

### Numpy Array의 인덱싱과 슬라이싱

* numpy에서 사용되는 인덱싱은 python에서의 인덱싱과 기본적으로 동일하다.
* numpy의 index는 0부터 시작한다.

In [57]:
# np.arange(시작, 끝, 스템, 데이터타입)
# 기본적으로 np.arange(10)
# ?np.arange
arr1 = np.arange(10,20, 2, dtype='int32')
print(arr1)
print(arr1.dtype)

arr1 = np.arange(10)
print(arr1)

# 1차원 인덱싱
print(arr1[0])
print(arr1[0:3])
print(arr1[:3])
print(arr1[3:])
print(arr1[:-3])
print(arr1[:])

[10 12 14 16 18]
int32
[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2]
[0 1 2]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [99]:
# 2차원인덱싱
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

# arr2(행, 요소위치)
print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])
print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])
print(arr2[2,0])
print(arr2[2,1])
print(arr2[2,2])

# 요소꺼내기
print(arr2[:]) # 전체 요소 꺼내기
print()
print(arr2[2:]) # 3번째행(2차원) 모든 요소 꺼내기
print(arr2[2,:]) # 3번째행(1차원) 모든 요소 꺼내기

print(arr2[2,2]) # 2행의 3번쨰요소 = 9
print(arr2[:,2]) # 모든열의 3번쨰요소

print(arr2[0:2, 0:2])
print(arr2[1:, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 8 9]]
[7 8 9]
9
[3 6 9]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [107]:
lst = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
a = np.array(lst)
 
# 정수 인덱싱
s = a[[0, 0], [0, 0]]
print(s)

[1 2]


### Numpy 함수

* zeros(n) : n개의 배열크기 만큼 0으로 채움
* ones(n)  : n개의 배열크기 만큼 1로 채움
* arange(n): n개의 배열크기 만큼 1씩 증가하는 배열을 생성
* random   : 0~1사이의 실수한개를 난수로 리턴   
* sum
* mean
* sort
* unique

##### 1개의 array에 적용되는 함수

In [83]:
# 1. zeros()
print(np.zeros(10))
print(np.zeros((10,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [84]:
# 2. ones()
print(np.ones(10))
print(np.ones((10,5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [85]:
# 3. arange()
print(np.arange(10,20, 2, dtype='int32'))

[10 12 14 16 18]


In [87]:
# 4. random
# np.random?
arr1 = np.random.rand(5,3)
print(arr1)

[[0.03824403 0.25681636 0.25049877]
 [0.87735379 0.36673088 0.32475822]
 [0.12084104 0.96585822 0.34534534]
 [0.55754504 0.98196458 0.69983795]
 [0.22989384 0.97116777 0.37972552]]


In [89]:
# 5. abs()
arr1 = np.random.randn(5,3)
print(arr1)
print(abs(arr1))

[[-1.36603898 -1.20739773  0.12648437]
 [ 0.74715698 -1.36194704  1.48735316]
 [ 0.81325913  1.02696933  0.94245767]
 [-1.09591001 -1.86183261  2.47942929]
 [-0.94618723  0.06424976 -0.61250007]]
[[1.36603898 1.20739773 0.12648437]
 [0.74715698 1.36194704 1.48735316]
 [0.81325913 1.02696933 0.94245767]
 [1.09591001 1.86183261 2.47942929]
 [0.94618723 0.06424976 0.61250007]]


In [90]:
# 6. square() : 각 요소의 제곱근을 계산
print(np.square(arr1))

[[1.86606249e+00 1.45780927e+00 1.59982948e-02]
 [5.58243560e-01 1.85489974e+00 2.21221941e+00]
 [6.61390410e-01 1.05466600e+00 8.88226463e-01]
 [1.20101874e+00 3.46642065e+00 6.14756960e+00]
 [8.95270271e-01 4.12803196e-03 3.75156335e-01]]


In [91]:
# 7. exp() : 각 요소의 무리수를 e지수로 계산
print(np.exp(arr1))

[[ 0.25511548  0.29897428  1.13483171]
 [ 2.1109899   0.25616153  4.42536675]
 [ 2.25524616  2.79258958  2.56628075]
 [ 0.33423531  0.15538761 11.93445137]
 [ 0.38821839  1.0663587   0.54199415]]


In [92]:
# 8. log() : 각 요소를 자연로그, 상용로그, 밑이 2인 로그
print(np.log(arr1))

[[        nan         nan -2.06763657]
 [-0.29147996         nan  0.39699814]
 [-0.20670549  0.02661207 -0.05926427]
 [        nan         nan  0.90802841]
 [        nan -2.74497725         nan]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


In [93]:
# 9. log10() : 상용로그
print(np.log10(arr1))

[[        nan         nan -0.89796315]
 [-0.12658814         nan  0.1724141 ]
 [-0.08977105  0.01155747 -0.02573815]
 [        nan         nan  0.39435173]
 [        nan -1.19212847         nan]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log10
  


In [94]:
#10. log2() : 밑이 2인 로그
print(np.log2(arr1))

[[        nan         nan -2.98296902]
 [-0.4205167          nan  0.57274724]
 [-0.29821298  0.0383931  -0.08550027]
 [        nan         nan  1.31000808]
 [        nan -3.96016507         nan]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log2
  


In [95]:
# 11. sign() : 각 요소의 값을 +인경는 1, -인경우 -1, 0인 경우는 0
np.sign(arr1)

array([[-1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  1.,  1.],
       [-1., -1.,  1.],
       [-1.,  1., -1.]])

In [ ]:
# 12. ceil()
np.ceil(arr1)

In [109]:
# 13. floor()
np.floor(arr1)

array([[-2., -2.,  0.],
       [ 0., -2.,  1.],
       [ 0.,  1.,  0.],
       [-2., -2.,  2.],
       [-1.,  0., -1.]])

In [112]:
# 14. isnan()
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [113]:
# 15. isinf()
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [114]:
# 16. cos(), sin(), tan(), cosh(), sinh(), tanh()

##### 2개의 array에 적용되는 함수

In [116]:
arr1 = np.random.randn(5,3)
arr2= np.random.randn(5,3)
print(arr1)
print(arr2)

[[ 1.2339996   1.39614429 -1.28659322]
 [ 1.1923043  -0.72794465 -1.43550167]
 [ 0.37389172  0.69448248  1.77196096]
 [-0.48640123  0.0533553  -0.587836  ]
 [-0.31483984 -0.68377261 -0.67857379]]
[[-2.8208849  -1.09220713 -1.84484487]
 [ 1.22445495  0.50186968 -0.82065423]
 [-1.10801671  0.24159314 -1.18674696]
 [ 1.28023196  1.37405714 -1.91387496]
 [ 0.6097643   0.90298514  0.36850876]]


In [118]:
# 2 개의 array 연산함수(add, subtract, multiply, divide)
np.multiply(arr1, arr2)
np.add(arr1, arr2)

array([[-1.5868853 ,  0.30393717, -3.13143808],
       [ 2.41675925, -0.22607497, -2.2561559 ],
       [-0.73412499,  0.93607562,  0.585214  ],
       [ 0.79383073,  1.42741244, -2.50171096],
       [ 0.29492446,  0.21921253, -0.31006503]])

In [119]:
# maximum, minimum
np.maximum(arr1, arr2)

array([[ 1.2339996 ,  1.39614429, -1.28659322],
       [ 1.22445495,  0.50186968, -0.82065423],
       [ 0.37389172,  0.69448248,  1.77196096],
       [ 1.28023196,  1.37405714, -0.587836  ],
       [ 0.6097643 ,  0.90298514,  0.36850876]])

##### 통계함수

* 통계함수를 통해서 넘파이배열의 총합 또는 평균들을 구할 때 사용
* 열의 합 또는 행의 합등을 구할 수 있다.

In [125]:
# 합계 : sum()
print(np.sum(arr1)) #  arr1의 전체
print(np.sum(arr1, axis=0)) #  arr1의 열의 합
print(np.sum(arr1, axis=1)) #  arr1의 행의 합

0.5146756439037253
[ 1.99895455  0.73226481 -2.21654372]
[ 1.34355068 -0.97114202  2.84033516 -1.02088193 -1.67718624]


In [126]:
# 평균 : mean()
print(np.mean(arr1)) #  arr1의 전체
print(np.mean(arr1, axis=0)) #  arr1의 열의 평균
print(np.mean(arr1, axis=1)) #  arr1의 행의 평균

0.03431170959358169
[ 0.39979091  0.14645296 -0.44330874]
[ 0.44785023 -0.32371401  0.94677839 -0.34029398 -0.55906208]


In [130]:
# 통계함수 : 표준편차(std), 분산(var), 최소값(min), 최대값(max)
print(np.std(arr1)) #  arr1의 전체
print(np.std(arr1, axis=0)) #  arr1의 열의 표준편차
print(np.std(arr1, axis=1)) #  arr1의 행의 표준편차
print()

print(np.var(arr1)) #  arr1의 전체
print(np.var(arr1, axis=0)) #  arr1의 열의 분산
print(np.var(arr1, axis=1)) #  arr1의 행의 분산
print()

print(np.min(arr1)) #  arr1의 전체
print(np.min(arr1, axis=0)) #  arr1의 열의 최소값
print(np.min(arr1, axis=1)) #  arr1의 행의 최소값
print()

print(np.max(arr1)) #  arr1의 전체
print(np.max(arr1, axis=0)) #  arr1의 열의 최대값
print(np.max(arr1, axis=1)) #  arr1의 행의 최대값
print()

0.9830516030317745
[0.7239732  0.81542353 1.15578832]
[1.22822182 1.11022306 0.5979907  0.28141555 0.17270425]

0.9663904542233417
[0.5241372  0.66491553 1.33584663]
[1.50852885 1.23259524 0.35759288 0.07919471 0.02982676]

-1.4355016704933539
[-0.48640123 -0.72794465 -1.43550167]
[-1.28659322 -1.43550167  0.37389172 -0.587836   -0.68377261]

1.7719609644631786
[1.2339996  1.39614429 1.77196096]
[ 1.39614429  1.1923043   1.77196096  0.0533553  -0.31483984]



In [131]:
# 위치함수 : 최소값(argmin), 최대값(argmax)이 위치한 인덱스를 리턴
print(np.argmin(arr1))
print(np.argmax(arr1))

5
8


In [132]:
# 누적함수 : 각 성분의 누적합(cumsum), 누적곱(cumprod)
print(np.cumsum(arr1))
print(np.cumprod(arr1))

[1.2339996  2.63014389 1.34355068 2.53585497 1.80791032 0.37240865
 0.74630037 1.44078285 3.21274381 2.72634258 2.77969788 2.19186188
 1.87702204 1.19324943 0.51467564]
[ 1.2339996   1.7228415  -2.21659619 -2.64285717  1.92385374 -2.76169526
 -1.03257498 -0.71710523 -1.27068248  0.61806152  0.03297686 -0.01938498
  0.00610317 -0.00417318  0.00283181]


##### 기타함수

In [142]:
# 배열정렬
print(arr1)
#print(np.sort(arr1))
print()
print(np.sort(arr1)[-2])
print(np.sort(arr1)[::-1])

print()
print(np.sort(arr1, axis=1))

[[ 1.2339996   1.39614429 -1.28659322]
 [ 1.1923043  -0.72794465 -1.43550167]
 [ 0.37389172  0.69448248  1.77196096]
 [-0.48640123  0.0533553  -0.587836  ]
 [-0.31483984 -0.68377261 -0.67857379]]

[-0.587836   -0.48640123  0.0533553 ]
[[-0.68377261 -0.67857379 -0.31483984]
 [-0.587836   -0.48640123  0.0533553 ]
 [ 0.37389172  0.69448248  1.77196096]
 [-1.43550167 -0.72794465  1.1923043 ]
 [-1.28659322  1.2339996   1.39614429]]

[[-1.28659322  1.2339996   1.39614429]
 [-1.43550167 -0.72794465  1.1923043 ]
 [ 0.37389172  0.69448248  1.77196096]
 [-0.587836   -0.48640123  0.0533553 ]
 [-0.68377261 -0.67857379 -0.31483984]]


In [145]:
# 중복제거 : unique()
names = np.array(['손흥민', '소향', '홍길동', '손흥민', '소향', '홍길순'])
print(names)
print(np.unique(names))

['손흥민' '소향' '홍길동' '손흥민' '소향' '홍길순']
['소향' '손흥민' '홍길동' '홍길순']


### 데이터분석 실습 - 영화평점데이터

* https://grouplens.org/datasets/movielens

In [152]:
# 영화평점데이터 업로드 : 약 100만건
#np.loadtxt?
data = np.loadtxt('./data/movielens/ratings.dat', 
                  delimiter='::', dtype=np.int64)

In [161]:
# 넘파이배열 [행범위, 열범위] : [2:,:3]
# [start:end, start:end]
# 첫5행만 출력
data[0:5,:]
data[1000000:1000010,]
data[1000000:1000010, :3]
data.shape
data[0:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [163]:
# 전체 평점의 평균
mean_rating_total = data[:,2].mean()
mean_rating_total

3.581564453029317

In [167]:
# 사용자id만 추출(중복제거)
user_ids = np.unique(data[:, 0])
user_ids.shape # 건수

(6040,)

In [180]:
# 사용자별 평점의 평균구하기



mean_values = []
for user_id in user_ids:
    # 첫번째열 = 사용자아이디
    # 1. user_id 1인행만추출해서 저장
    data_for_user = data[data[:,0] == user_id, :]
    #print(data_for_user)
    #break
    # 2. data_for_user을 평균 : 3번째열의 평균
    value = data_for_user[:,2].mean()
    #print(value)
    #break
    # 3. 평균을 mean_values에 추가
    # 사용자id, 평균값
    mean_values.append([user_id, value])
    #print(mean_values)
    #break
    
print(mean_values[:5]) # 다섯행만 출력
print(type(mean_values))

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
<class 'list'>


In [182]:
mean_array = np.array(mean_values, dtype=np.float32)
mean_array[:5]
mean_array.shape

(6040, 2)

In [184]:
# 데이터분석결과를 파일로 저장하기
# savetxt()
#np.savetxt?
np.savetxt('./data/movielens/user_ratings_mean.csv',
              mean_array, fmt='%.1f', delimiter=',')
# 파일생성확인

### 연습문제

* 영화별 평점을 구해서 `movie_ratings_mean.csv`로 저장
* 영화ID, 영화명, 평균평점

* 주의사항
 - movies.dat
 - 3845::And God Created Woman (Et Dieu la Femme) (1956)::Drama로 수정
   (영문자가 아닌 문자를 삭제)
 - 파이썬 3.x에서 ansi파일("movies_chg.dat")로 저장

In [185]:
data_user  = np.loadtxt('./data/movielens/ratings.dat', 
                  delimiter='::', dtype=np.int64)
data_movie = np.loadtxt('./data/movielens/movies_chg.dat', 
                  delimiter='::', encoding ='utf-8', dtype=np.str)

In [197]:
#data_user[:5]
#data_movie[1193:1195]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [199]:
# 사용자가 1번인 id
data_user[:,1]

# 영화제목 조인
# data[data[:,0] == user_id, :]
data_movie[:,0:2]

data_movie[data_movie[:,0] == str(1193), 1]

array(["One Flew Over the Cuckoo's Nest (1975)"], dtype='<U82')

In [209]:
# 영화평점의 평균하기

movie_ids = np.unique(data_user[:,1]) # data_user에서 영화ID중복제거

mean_values = [] # 영화ID, 영화제목, 평점평균

for movie_id in movie_ids:
    
    # 1. user에서 movie_id와 같은 
    data_for_movie = data_user[data_user[:,1] == movie_id, :]
    #rint(data_for_movie)
    #reak
    
    # 2. 영화별 평균
    value = data_for_movie[:,2].mean()
    #print(value)
    #break
    
    # 3. 영화이름
    movie_name = data_movie[data_movie[:,0] == str(movie_id), 1]
    #print(movie_name)
    #break
    
    # 4. 평균을 mean_values([영화ID, 영화이름, 평균])
    mean_values.append([movie_id, movie_name[0].replace(',', ' '), value]);


print(mean_values[:5])

[[1, 'Toy Story (1995)', 4.146846413095811], [2, 'Jumanji (1995)', 3.20114122681883], [3, 'Grumpier Old Men (1995)', 3.01673640167364], [4, 'Waiting to Exhale (1995)', 2.7294117647058824], [5, 'Father of the Bride Part II (1995)', 3.0067567567567566]]


In [210]:
# 파일생성 : movie_ratings_mean.csv
mean_array = np.array(mean_values, dtype=np.str)
np.savetxt('./data/movielens/movie_ratings_mean.csv',
              mean_array, fmt='%s', delimiter=',')