# Numpy 함수

* random
    - 0~1 사이의 실수 1개를 난수로 리턴
* sum
* mean
    - 통계 관련 함수
* sort
* unique
    - 중복 제거 함수
* zeros(n)
    - n개의 배열 크기만큼 0으로 채워주는 함수
* ones
    - n개의 배열 크기만큼 1로 채움
* arange(n)
    - n개의 배열 크기만큼 1씩 증가

In [14]:
import numpy as np

arr1 = np.random.randn(5, 3)
arr2 = np.random.randn(5, 3)

print(arr1)
print()
print(arr2)

[[-0.49712953 -0.61070785 -0.02276788]
 [-0.36110897 -0.07356778  2.02410293]
 [-0.49418568 -0.42194301 -0.41785151]
 [ 0.58079398 -0.16039323 -0.42445345]
 [ 1.66629442 -1.34850487  0.57646398]]

[[-1.327537   -0.66690497  0.76608357]
 [-0.44567146  0.82592924  0.17785637]
 [-0.5074933   0.64379296 -1.88284983]
 [-0.38693557 -0.49176588  0.64486202]
 [ 1.20454677 -0.24162749  0.44146612]]


### 1개의 Array에 적용되는 함수

In [16]:
 # print(dir(np))

print("-------- zeros --------")
print(np.zeros(10))
print(np.zeros((10, 5)))
print("-----------------------")
print()

print("-------- ones --------")
print(np.ones(10))
print(np.ones((10, 5)))
print("-----------------------")
print()

# random

# np.random?
# ==================== =========================================================
# Compatibility functions
# ==============================================================================
# rand                 Uniformly distributed values.
# randn                Normally distributed values.
# ranf                 Uniformly distributed floating point numbers.
# randint              Uniformly distributed integers in a given range.
# ==================== =========================================================

arr1 = np.random.randn(5, 3)
print(arr1)
print(abs(arr1))
print("-"*50)

# square : 각 요소의 제곱근 계산
print(np.square(arr1))
print("-"*50)

# exp
# 각 요소의 무리수를 e지수로 계산하기
print(np.exp(arr1))
print("-"*50)

# log() : 각 요소를 자연로그
print(np.log(arr1))
print("-"*50)

# log10() : 상용로그
print(np.log10(arr1))
print("-"*50)

# log2() : 밑이 2인 로그
print(np.log2(arr1))
print("-"*50)

# sign() : 각 요소의 값을
# +인 경우 1
# -인 경우 -1
# 0인 경우 0
print(np.sign(arr1))
print("-"*50)
# 얘가 왜 필요하냐면~
# sigmoid? 라는 게 있다 어쩌고저쩌고이러쿵저러쿵쉬는시간주세요
# input이 들어왔을 때 output이 0아니면 1 나오게 처리해야하는 경우가 있음

# ceil() : 정수 중 가장 큰 값 가져옴
np.ceil(arr1)
print("-"*50)

# floor()
np.floor(arr1)
print("-"*50)

# isnan()
np.isnan(arr1)
print("-"*50)

# isinf()
np.isinf(arr1)
print("-"*50)

# cos()
np.cos(arr1)
print("-"*50)

# sin()
np.sin(arr1)
print("-"*50)

# tan()
np.tan(arr1)
print("-"*50)

# cosh()
np.cosh(arr1)
print("-"*50)

# sinh()
np.sinh(arr1)
print("-"*50)

# tanh()
np.tanh(arr1)

-------- zeros --------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-----------------------

-------- ones --------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-----------------------

[[-0.40002695  0.24387328 -0.3138137 ]
 [ 0.62949523  0.27932802 -0.24677382]
 [-0.85735802 -0.24506736 -0.60228015]
 [-0.19017714  1.68820615 -0.64579032]
 [ 0.46540278  0.07751848 -0.38291483]]
[[0.40002695 0.24387328 0.3138137 ]
 [0.62949523 0.27932802 0.24677382]
 [0.85735802 0.24506736 0.60228015]
 [0.19017714 1.68820615 0.64579032]
 [0.46540278 0.07751848 0.38291483]]
--------------------------------------------------
[[0.16002156 0.05947418 0.09847904]
 [0.39626425 

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: RuntimeWarning: invalid value encountered in log
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:46: RuntimeWarning: invalid value encountered in log10
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:50: RuntimeWarning: invalid value encountered in log2


array([[-0.37997203,  0.23915087, -0.30390258],
       [ 0.55770455,  0.27228303, -0.24188361],
       [-0.69489395, -0.24027634, -0.53867008],
       [-0.18791709,  0.93391835, -0.56882922],
       [ 0.43447737,  0.07736358, -0.36523615]])

### 2개의 Array에 적용되는 함수

In [9]:
# 2개의 array 연산함수(사칙연산)
print(np.multiply(arr1, arr2))
print()
print(np.add(arr1, arr2))

[[ 0.34471978  0.33299761 -3.80165336]
 [-0.39450452  0.01397247 -0.08472363]
 [-0.03697775 -0.5677075   2.24951121]
 [-0.06399537 -0.10273428  0.52603207]
 [-0.93912968 -0.01649497  0.06160726]]

[[-1.21337774e+00  1.60943827e+00  4.03804256e-01]
 [-1.43233774e+00  1.03260765e+00  1.63984487e+00]
 [-1.14963728e-01 -4.04233567e-01 -3.19083030e+00]
 [-1.83792698e-03  7.60701725e-01 -2.50125698e+00]
 [-6.84940425e-01 -1.16832456e+00  7.07509319e-01]]


In [13]:
# maximum, minimum

print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[[-0.45387656  1.36558924  2.16211075]
 [ 0.23640783  1.01889429  1.68997785]
 [ 0.14322168  0.57798494 -1.05150496]
 [ 0.25205577  0.87774513 -0.23178623]
 [ 0.68535055  0.01395188  0.60581635]]

[[-0.75950118  0.24384903 -1.75830649]
 [-1.66874557  0.01371336 -0.05013298]
 [-0.25818541 -0.98221851 -2.13932533]
 [-0.2538937  -0.1170434  -2.26947075]
 [-1.37029098 -1.18227644  0.10169297]]


# 자주 사용하는 통계 함수

* 통계 함수를 통해서 Numpy 배열의 총합 또는 평균들을 구할 때 사용
* 열의 합 또는 행의 합 등을 구할 수 있음

In [18]:
# 합계 : sum()
print(np.sum(arr1)) # arr1 전체
print("-"*50)

print(np.sum(arr1, axis=1)) # arr1 행의 합
print("-"*50)

print(np.sum(arr1, axis=0)) # arr1 열의 합

-0.5003783515735265
--------------------------------------------------
[-0.46996737  0.66204944 -1.70470553  0.85223869  0.16000643]
--------------------------------------------------
[-0.3526641   2.04385856 -2.19157282]


In [19]:
# 평균 : mean()
print(np.mean(arr1)) # arr1 전체
print("-"*50)

print(np.mean(arr1, axis=1)) # arr1 행의 평균
print("-"*50)

print(np.mean(arr1, axis=0)) # arr1 열의 평균

-0.03335855677156843
--------------------------------------------------
[-0.15665579  0.22068315 -0.56823518  0.28407956  0.05333548]
--------------------------------------------------
[-0.07053282  0.40877171 -0.43831456]


In [24]:
# 통계함수 : 표준편차(std), 분산(var), 최솟값(min), 최댓값(max)
print("------------------표준편차------------------")
print(np.std(arr1))
print("-"*50)
print(np.std(arr1, axis=1))
print("-"*50)
print(np.std(arr1, axis=0))
print()
print("------------------분산------------------------")
print(np.var(arr1))
print("-"*50)
print(np.var(arr1, axis=1))
print("-"*50)
print(np.var(arr1, axis=0))
print()
print("------------------최솟값------------------------")
print(np.min(arr1))
print("-"*50)
print(np.min(arr1, axis=1))
print("-"*50)
print(np.min(arr1, axis=0))
print()
print("------------------최댓값------------------------")
print(np.max(arr1))
print("-"*50)
print(np.max(arr1, axis=1))
print("-"*50)
print(np.max(arr1, axis=0))
print()

------------------표준편차------------------
0.6146443888870947
--------------------------------------------------
[0.28539544 0.36013079 0.25112315 1.01014007 0.34674612]
--------------------------------------------------
[0.55122432 0.66605313 0.15823297]

------------------분산------------------------
0.3777877247903902
--------------------------------------------------
[0.08145056 0.12969419 0.06306284 1.02038297 0.12023287]
--------------------------------------------------
[0.30384826 0.44362678 0.02503767]

------------------최솟값------------------------
-0.8573580172981843
--------------------------------------------------
[-0.40002695 -0.24677382 -0.85735802 -0.64579032 -0.38291483]
--------------------------------------------------
[-0.85735802 -0.24506736 -0.64579032]

------------------최댓값------------------------
1.6882061510593145
--------------------------------------------------
[ 0.24387328  0.62949523 -0.24506736  1.68820615  0.46540278]
---------------------------------------

In [27]:
# 위치함수 : 최솟값(argmin), 최댓값(argmax)이 위치한 idx 리턴
print(np.argmin(arr1))
print(np.argmax(arr1))

6
10


In [28]:
# 누적함수 : 각 성분의 누적합(cumsum), 누적곱(cumprod)
print(np.cumsum(arr1))
print(np.cumprod(arr1))

[-0.40002695 -0.15615367 -0.46996737  0.15952786  0.43885588  0.19208206
 -0.66527595 -0.91034332 -1.51262347 -1.7028006  -0.01459445 -0.66038478
 -0.194982   -0.11746352 -0.50037835]
[-4.00026954e-01 -9.75558867e-02  3.06143738e-02  1.92716024e-02
  5.38309848e-03 -1.32840775e-03  1.13892104e-03 -2.79112375e-04
  1.68103843e-04 -3.19695076e-05 -5.39711193e-05  3.48540266e-05
  1.62211608e-05  1.25743968e-06 -4.81492299e-07]


# 기타 함수

In [41]:
# sort() : 배열 정렬

print(arr1)
print("-"*50)
print("-"*50)
print("-"*50)

print(np.sort(arr1)) # 오름차순
print("-"*50)
print(np.sort(arr1)[::-1]) # 내림차순
print("-"*50)
print(np.sort(arr1, axis=1)) # 

[[-0.40002695  0.24387328 -0.3138137 ]
 [ 0.62949523  0.27932802 -0.24677382]
 [-0.85735802 -0.24506736 -0.60228015]
 [-0.19017714  1.68820615 -0.64579032]
 [ 0.46540278  0.07751848 -0.38291483]]
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
[[-0.40002695 -0.3138137   0.24387328]
 [-0.24677382  0.27932802  0.62949523]
 [-0.85735802 -0.60228015 -0.24506736]
 [-0.64579032 -0.19017714  1.68820615]
 [-0.38291483  0.07751848  0.46540278]]
--------------------------------------------------
[[-0.38291483  0.07751848  0.46540278]
 [-0.64579032 -0.19017714  1.68820615]
 [-0.85735802 -0.60228015 -0.24506736]
 [-0.24677382  0.27932802  0.62949523]
 [-0.40002695 -0.3138137   0.24387328]]
--------------------------------------------------
[[-0.40002695 -0.3138137   0.24387328]
 [-0.24677382  0.27932802  0.62949523]
 [-0.85735802 -0.60228015 -0.24506736]
 [-0.64579032 -0.19017714  1.68820615]
 

In [43]:
# unique 함수 : 중복 제거 함수

names = np.array(["사자", "기린", "오리", "토끼", "호랑이", "오리", "토끼", "고양이"])
print(names)
print(np.unique(names))

['사자' '기린' '오리' '토끼' '호랑이' '오리' '토끼' '고양이']
['고양이' '기린' '사자' '오리' '토끼' '호랑이']
