# 데이터 분석 실습 - 영화평점데이터

* https://grouplens.org/datasets/movielens

* `1` 다운로드
* `2` 해제
* `3` 업로드

In [3]:
import numpy as np

In [3]:
# 영화평점데이터 업로드 : 약 100만건
# np.loadtxt?
'''
Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None, << 얘가 중요해!!!!!!!
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
)
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.
'''

In [4]:
data = np.loadtxt('./data/movielens/ratings.dat', delimiter="::", dtype=np.int64)

# Numpy 배열 [행 범위, 열 범위] : [2:,:3]
# 이거 뭐냐!?

In [99]:
# Numpy 배열 [행 범위, 열 범위] : [2:,:3]
# [row start:end, col start:end]

# 첫 5행만 출력
# data[0:5,:]
# data[1000000:1000010,]
# data[1000000:1000010, :3]
# data.shape
# print(data)

In [21]:
# 전체 평점의 평균
# data에서 3번째 열을 가져오면~

mean_rating_total = data[:,2].mean()
print(mean_rating_total)

3.581564453029317


In [35]:
# 사용자 id만 추출

user_ids = np.unique(data[:,0])
print("사용자 id 중복제거 추출 : ", user_ids)
print("건수 : ", user_ids.shape)

사용자 id 중복제거 추출 :  [   1    2    3 ... 6038 6039 6040]
건수 :  (6040,)


In [20]:
# 사용자별 평점의 평균

user_ids = np.unique(data[:,0])
mean_values = []

for user_id in user_ids:
    # print(user_id, end=",")
    
    # 1. user_id 1인행만 추출해서 저장
    data_for_user = data[data[:,0] == user_id, :]
    # print(data_for_user)
    
    # 2. data_for_user 평균
    value = data_for_user[:,2].mean()
    # print(value)
    
    # 3. 평균을 mean_values에 추가
    mean_values.append([user_id, value])
    # print(mean_values)
    # break
    
# 4. 다섯행만 출력
print(mean_values[:5])
print(type(mean_values))
    

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
<class 'list'>


In [22]:
mean_array = np.array(mean_values, dtype=np.float32)
mean_array[:5]
mean_array.shape

(6040, 2)

In [23]:
# 데이터 분석 결과를 파일로 저장하기
# savetxt(fileName)

# 데이터 분석 결과를 아래의 경로에, 아래의 확장자로 저장하는데
# 그 안에 내용은 mean_array로 채울 거고
# mean_array에 있는 데이터 값의 포맷은 .1f로 설정하겠다
np.savetxt("./data/movielens/user_ratigns_mean.csv", mean_array, fmt="%.1f", delimiter=",")

# 연습문제

* 영화별 평점을 구해서 **movie_ratings_mean.csv**로 저장
* 영화id, 영화 제목, 평균 평점
* 주의 사항
    - `1` movies.dat에 3845 수정
        > 3845::And God Created Woman (Et Dieu Cr la Femme) (1956)::Drama
    - `2` Python 3.x에서 ANSI 파일로 저장

In [33]:
data_user = np.loadtxt('./data/movielens/ratings.dat', delimiter="::", dtype=np.int64)
data_movie = np.loadtxt("./data/movielens/movies_chg.dat", delimiter="::", encoding="utf-8", dtype=np.str)

In [34]:
print(data_user[:5])
print(data_movie[:5])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
[['1' 'Toy Story (1995)' "Animation|Children's|Comedy"]
 ['2' 'Jumanji (1995)' "Adventure|Children's|Fantasy"]
 ['3' 'Grumpier Old Men (1995)' 'Comedy|Romance']
 ['4' 'Waiting to Exhale (1995)' 'Comedy|Drama']
 ['5' 'Father of the Bride Part II (1995)' 'Comedy']]


In [73]:
# 사용자가 1번인 id
# data_user[:1]

# 영화제목 조인
# data[data[:,0] == user_id, :]
# data_movie[:,0:2]

# data_movie[data_movie[:,0] == str(1193), 1]
# array(["One Flew Over the Cuckoo's Nest (1975)"], dtype='<U82')

# 영화 평점 평균 구하기
movie_ids = np.unique(data_user[:,1]) # data_user에서 영화id중복제거
# print(movie_ids)

# mean_values = [] # 영화 id, 영화제목, 평점 평균

for movie_id in movie_ids:
    # print(movie_id, end=",")
    
    # 1. user에서 추출한 movie_id와 같은 애를 가져와서
    # data_for_movie = 여기에 넣어라
    data_for_movie = data_movie[data_movie[:,0] == str(movie_id)]
    # print(data_for_movie)
    # break

    
    # 2. 영화별 평균 구해라
    # movie_mena = ???
    # value = data_for_user[:,2].mean()
    # value = data_user
    
    # 2.5. 영화 이름
    movie_name = data_for_movie[:,1]
    # print(movie_name)
    # break
    
    # 3. mean_values([영화id, 영화제목, 평점평균])
    mean_values.append([movie_id, movie_name, 0])

print(mean_values[:5])

[[1, array(['Toy Story (1995)'], dtype='<U82'), 0], [2, array(['Jumanji (1995)'], dtype='<U82'), 0], [3, array(['Grumpier Old Men (1995)'], dtype='<U82'), 0], [4, array(['Waiting to Exhale (1995)'], dtype='<U82'), 0], [5, array(['Father of the Bride Part II (1995)'], dtype='<U82'), 0]]


In [82]:
# mean_array = np.array(mean_values, dtype=np.str)
# np.savetxt("./data/movielens/movie_ratings_mean1.csv", mean_array, delimiter=",")

ValueError: setting an array element with a sequence

# 강사님

In [91]:
movie_ids = np.unique(data_user[:,1])
mean_values = []

for movie_id in movie_ids:
    
    data_for_movie = data_user[data_user[:,1] == movie_id, :]
    # print(data_for_movie)
    # break
    # 왜 user를 써서 하는 건데?
    # 왜?
    # 왜?!
    # 왜!!!!!?!?
    
    value = data_for_movie[:,2].mean()
    # print(value)
    # break
    
    movie_name = data_movie[data_movie[:,0] == str(movie_id), 1]
    # print(movie_name)
    # break
    
    mean_values.append([movie_id, movie_name[0].replace(",", " "), value])
    
print(mean_values[:5])

[[1, 'Toy Story (1995)', 4.146846413095811], [2, 'Jumanji (1995)', 3.20114122681883], [3, 'Grumpier Old Men (1995)', 3.01673640167364], [4, 'Waiting to Exhale (1995)', 2.7294117647058824], [5, 'Father of the Bride Part II (1995)', 3.0067567567567566]]


In [94]:
mean_array = np.array(mean_values, dtype=np.str)
np.savetxt("./data/movielens/moive_ratigns_mean.csv", mean_array, fmt="%s", delimiter=",")