# Numpy (Numerical Python)

* list = vector = Python - 1차원 list = Pandas - Series
* [[]] = 행렬 = Python - 2차원 list = Pandas - Data Frame
* Numpy에서는 vector 및 행렬 연산에 특화된 라이브러리
* Array 단위로 데이터 관리
    - 행렬(Matrix)과 유사함
    - **기본적으로 Array 단위로 관리 및 연산 수행**
* Pandas와 함께 데이터 분석에 많이 사용
* 수치해석용 Python Lib

# Reference

* [Home](http://www.numpy.org)
* [Docs](http://docs.scipy.org/doc)
* [Tutrial 1](http://www.scipy-lectures.org/intro/numpy/index.html)
* [Tutrial 2](https://docs.scipy.org/doc/numpy/user/quickstart.html)


In [5]:
import numpy as np

# print(dir(np))

# Numpy 사용 시 version 확인하는 습관 들이기
# Python은 version에 민감하기 때문에, 호환성 등 체크 필수
np.__version__

'1.16.5'

# 1차원 Array 정의 및 사용

In [20]:
data = [1, 2, 3, 4, 5]
print(type(data))

# Python의 list를 Numpy의 배열(ndarray)로 변경
# arr = np.array?
# Docstring:
# array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
# 보통 array 생성 시 위의 옵션값들은 잘 사용하지 않는다.
# Array 생성 시 자동으로 형변환(Upcasting)함
# 왜 ndarray로 변경하냐?
    # Pandas에서 ndarray를 받는대~
    
arr = np.array(data)
print(arr)
print(type(arr)) # <class 'numpy.ndarray'>

# Upcasting : 강제 형변환
casting_arr = np.array([1, 2, 3.0])
print(casting_arr) # [1. 2. 3.]

print()

# np.shape : numpy 배열 크기 리턴
# Return : tuple of ints
# np.shape?

print(np.shape(arr))

# array가 np로 되어 있기 때문에 이렇게도 사용 가능
print(arr.shape)
# help(arr.shape)

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 2. 3.]

(5,)
(5,)


# 2차원 Array(행렬, Matrix) 정의 및 사용

In [31]:
data = [[1, 2, 3], [4, 5, 6]]
print(data)
print(type(data))

# 2차원 리스트를 Numpy의 2차원 배열로 변환하기
arr = np.array(data)
print(arr)
print(type(arr))
print(arr.shape) # (2, 3) == 2행 3열

# 2차원 array 직접 선언하기
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# Numpy Data Type 확인하기
print(arr.dtype)

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


# Numpy 연산

* ### Numpy shape
---
* Numpy에서 해당 Array 크기를 확인할 수 있는 함수
    - Return : 정수(int)
* shape(크기)를 확인함으로써 Numpy 배열에 몇 개의 데이터가 있는지, 몇 차원의 데이터인지 확인
* 1차원 배열인 경우 **(5, )** 형태로 리턴
* 2차원 배열인 경우 **(3, 4)** 형태로 리턴

* ### Numpy Data Type 
---
* int(8, 16, 32, 64)
    - 부호가 있는 정수
* uint(8, 16, 32, 64)
    - 부호가 없는 정수
* float(16, 32, 64, 128)
    - 실수
* complex(64, 128, 256)
    - 복소수
* bool
    - boolean
* string_
    - 문자열
    - 언더바(\_) 붙여서 표현
* object
    - Python Obejct(객체)
* unicode_
    - 유니코드
    - 언더바(\_) 붙여서 표현

In [35]:
# Numpy 배열 연산
# 조건
    # 배열 연산 시 배열 크기는 반드시 동일해야 함
    # 동일하지 않으면 오류 발생
    
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print(arr1+arr2)
print("-"*50)

print(arr1-arr2)
print("-"*50)

print(arr1*arr2)
print("-"*50)

print(arr1/arr2)
print("-"*50)

print(arr1 * 2)
print("-"*50)

print(arr1 ** 2)

[[ 8 10 12]
 [14 16 18]]
--------------------------------------------------
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------------------------------------
[[ 7 16 27]
 [40 55 72]]
--------------------------------------------------
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
--------------------------------------------------
[[ 2  4  6]
 [ 8 10 12]]
--------------------------------------------------
[[ 1  4  9]
 [16 25 36]]


In [38]:
# Array Broadcast
# Numpy 배열에서는 크기가 동일해야 연산이 가능하지만
# Numpy에서는 Broadcast 기능 제공해줌
# Broadcast
    # 서로 크기가 다른 Numpy 배열을 연산 가능하도록 해주는 기능
    # 아래 예제에서, 사실 행이 1개만 있는 거지만 내부적으로 2개를 만들어서(?) 연산이 가능하도록 해주는 것
    
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([7, 8, 9])
# arr2 = np.array([7, 8, 9, 10]) # 얘는 오류야 ValueError

print(arr1.shape) # (2, 3)
print(arr2.shape) # (3, )

(2, 3)
(3,)


# Numpy Array의 인덱싱과 슬라이싱

* Numpy에서 사용되는 indexing은 Python에서의 indexing과 기본적으로 동일
* Numpy의 index는 0부터 시작함

In [45]:
# ?np.arange
# Return : ndarray
# 리턴값을 빼면 Python range와 비슷함
# Docstring:
# arange([start,] stop[, step,], dtype=None)

print(np.arange(10))
print("-"*50)

arr1 = np.arange(10)
print(arr1)
print(arr1.dtype)
print("-"*50)

arr1 = np.arange(10, 20)
print(arr1)
print(arr1.dtype)
print("-"*50)

arr1 = np.arange(10, 20, 2)
print(arr1)
print(arr1.dtype)


[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
int32
--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
int32
--------------------------------------------------
[10 12 14 16 18]
int32


In [53]:
# Numpy 1차원 배열 Indexing 하기~

arr1 = np.arange(10)
print(arr1)

print(arr1[0])
print("-"*50)

print(arr1[9])
print("-"*50)

print(arr1[0:3])
print("-"*50)

print(arr1[:4])
print("-"*50)

print(arr1[4:])
print("-"*50)

print(arr1[:-1])

[0 1 2 3 4 5 6 7 8 9]
0
--------------------------------------------------
9
--------------------------------------------------
[0 1 2]
--------------------------------------------------
[0 1 2 3]
--------------------------------------------------
[4 5 6 7 8 9]
--------------------------------------------------
[0 1 2 3 4 5 6 7 8]


In [82]:
# Numpy 2차원 배열 Indexing 하기~
# arr(차원, 요소 위치)

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr1)
print("-"*50)

print(arr1[0,0])
print("-"*50)

print(arr1[0,1])
print("-"*50)

print(arr1[0,2])
print("-"*50)

print(arr1[1,0])
print("-"*50)

print(arr1[1,1])
print("-"*50)

print(arr1[1,2])
print("-"*50)

# 3행 요소 전부 꺼내기
print(arr1[2:]) # 2차원
print("-"*50)
print(arr1[2,:]) # 1차원
print("-"*50)

# 2행 3번째 요소 꺼내기
print(arr1[1:2, -1])
print("-"*50)

print(arr1[1,2])
print("-"*50)

# 모든 열의 3번째 요소 꺼내기
print(arr1[:, -1])
print("-"*50)

print(arr1[:, 2])
print("-"*50)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
1
--------------------------------------------------
2
--------------------------------------------------
3
--------------------------------------------------
4
--------------------------------------------------
5
--------------------------------------------------
6
--------------------------------------------------
[[7 8 9]]
--------------------------------------------------
[7 8 9]
--------------------------------------------------
[6]
--------------------------------------------------
6
--------------------------------------------------
[3 6 9]
--------------------------------------------------
[3 6 9]
--------------------------------------------------
